import { FEATURES } from './SiteMapUtils';

const deferredJSON = {
  [FEATURES.TOWER_AIRSHEDS.KEY]: {
  },
  [FEATURES.AQUATIC_REACHES.KEY]: {
    ARIK: () => import('./deferredJSON/AQUATIC_REACHES/ARIK.json'),
    BIGC: () => import('./deferredJSON/AQUATIC_REACHES/BIGC.json'),
    BLDE: () => import('./deferredJSON/AQUATIC_REACHES/BLDE.json'),
    BLUE: () => import('./deferredJSON/AQUATIC_REACHES/BLUE.json'),
    BLWA: () => import('./deferredJSON/AQUATIC_REACHES/BLWA.json'),
    CARI: () => import('./deferredJSON/AQUATIC_REACHES/CARI.json'),
    COMO: () => import('./deferredJSON/AQUATIC_REACHES/COMO.json'),
    CUPE: () => import('./deferredJSON/AQUATIC_REACHES/CUPE.json'),
    FLNT: () => import('./deferredJSON/AQUATIC_REACHES/FLNT.json'),
    GUIL: () => import('./deferredJSON/AQUATIC_REACHES/GUIL.json'),
    HOPB: () => import('./deferredJSON/AQUATIC_REACHES/HOPB.json'),
    KING: () => import('./deferredJSON/AQUATIC_REACHES/KING.json'),
    LECO: () => import('./deferredJSON/AQUATIC_REACHES/LECO.json'),
    LEWI: () => import('./deferredJSON/AQUATIC_REACHES/LEWI.json'),
    OKSR: () => import('./deferredJSON/AQUATIC_REACHES/OKSR.json'),
    POSE: () => import('./deferredJSON/AQUATIC_REACHES/POSE.json'),
    PRIN: () => import('./deferredJSON/AQUATIC_REACHES/PRIN.json'),
    MART: () => import('./deferredJSON/AQUATIC_REACHES/MART.json'),
    MAYF: () => import('./deferredJSON/AQUATIC_REACHES/MAYF.json'),
    MCDI: () => import('./deferredJSON/AQUATIC_REACHES/MCDI.json'),
    MCRA: () => import('./deferredJSON/AQUATIC_REACHES/MCRA.json'),
    REDB: () => import('./deferredJSON/AQUATIC_REACHES/REDB.json'),
    SYCA: () => import('./deferredJSON/AQUATIC_REACHES/SYCA.json'),
    TECR: () => import('./deferredJSON/AQUATIC_REACHES/TECR.json'),
    TOMB: () => import('./deferredJSON/AQUATIC_REACHES/TOMB.json'),
    WALK: () => import('./deferredJSON/AQUATIC_REACHES/WALK.json'),
    WLOU: () => import('./deferredJSON/AQUATIC_REACHES/WLOU.json'),
  },
  [FEATURES.FLIGHT_BOX_BOUNDARIES.KEY]: {
    ABBY: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/ABBY.json'),
    ARIK: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/ARIK.json'),
    BARC: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BARC.json'),
    BARR: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BARR.json'),
    BART: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BART.json'),
    BIGC: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BIGC.json'),
    BLAN: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BLAN.json'),
    BLDE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BLDE.json'),
    BLUE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BLUE.json'),
    BLWA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BLWA.json'),
    BONA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/BONA.json'),
    CARI: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/CARI.json'),
    CLBJ: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/CLBJ.json'),
    COMO: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/COMO.json'),
    CPER: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/CPER.json'),
    CRAM: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/CRAM.json'),
    CUPE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/CUPE.json'),
    DCFS: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/DCFS.json'),
    DEJU: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/DEJU.json'),
    DELA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/DELA.json'),
    DSNY: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/DSNY.json'),
    FLNT: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/FLNT.json'),
    GRSM: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/GRSM.json'),
    GUAN: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/GUAN.json'),
    GUIL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/GUIL.json'),
    HARV: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/HARV.json'),
    HEAL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/HEAL.json'),
    HOPB: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/HOPB.json'),
    JERC: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/JERC.json'),
    JORN: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/JORN.json'),
    KING: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/KING.json'),
    KONA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/KONA.json'),
    KONZ: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/KONZ.json'),
    LAJA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/LAJA.json'),
    LECO: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/LECO.json'),
    LENO: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/LENO.json'),
    LEWI: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/LEWI.json'),
    LIRO: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/LIRO.json'),
    MART: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MART.json'),
    MAYF: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MAYF.json'),
    MCDI: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MCDI.json'),
    MCRA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MCRA.json'),
    MLBS: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MLBS.json'),
    MOAB: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/MOAB.json'),
    NIWO: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/NIWO.json'),
    NOGP: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/NOGP.json'),
    OAES: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/OAES.json'),
    OKSR: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/OKSR.json'),
    ONAQ: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/ONAQ.json'),
    ORNL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/ORNL.json'),
    OSBS: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/OSBS.json'),
    POSE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/POSE.json'),
    PRIN: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/PRIN.json'),
    PRLA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/PRLA.json'),
    PROP: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/PROP.json'),
    REDB: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/REDB.json'),
    RMNP: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/RMNP.json'),
    SCBI: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SCBI.json'),
    SERC: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SERC.json'),
    SJER: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SJER.json'),
    SOAP: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SOAP.json'),
    SRER: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SRER.json'),
    STEI: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/STEI.json'),
    STER: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/STER.json'),
    SUGG: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SUGG.json'),
    SYCA: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/SYCA.json'),
    TALL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TALL.json'),
    TEAK: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TEAK.json'),
    TECR: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TECR.json'),
    TOMB: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TOMB.json'),
    TOOK: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TOOK.json'),
    TOOL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TOOL.json'),
    TREE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/TREE.json'),
    UKFS: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/UKFS.json'),
    UNDE: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/UNDE.json'),
    WALK: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/WALK.json'),
    WLOU: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/WLOU.json'),
    WOOD: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/WOOD.json'),
    WREF: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/WREF.json'),
    YELL: () => import('./deferredJSON/FLIGHT_BOX_BOUNDARIES/YELL.json'),
  },
  [FEATURES.SAMPLING_BOUNDARIES.KEY]: {
    ABBY: () => import('./deferredJSON/SAMPLING_BOUNDARIES/ABBY.json'),
    BARR: () => import('./deferredJSON/SAMPLING_BOUNDARIES/BARR.json'),
    BART: () => import('./deferredJSON/SAMPLING_BOUNDARIES/BART.json'),
    BLAN: () => import('./deferredJSON/SAMPLING_BOUNDARIES/BLAN.json'),
    BONA: () => import('./deferredJSON/SAMPLING_BOUNDARIES/BONA.json'),
    CLBJ: () => import('./deferredJSON/SAMPLING_BOUNDARIES/CLBJ.json'),
    CPER: () => import('./deferredJSON/SAMPLING_BOUNDARIES/CPER.json'),
    DCFS: () => import('./deferredJSON/SAMPLING_BOUNDARIES/DCFS.json'),
    DEJU: () => import('./deferredJSON/SAMPLING_BOUNDARIES/DEJU.json'),
    DELA: () => import('./deferredJSON/SAMPLING_BOUNDARIES/DELA.json'),
    DSNY: () => import('./deferredJSON/SAMPLING_BOUNDARIES/DSNY.json'),
    GRSM: () => import('./deferredJSON/SAMPLING_BOUNDARIES/GRSM.json'),
    GUAN: () => import('./deferredJSON/SAMPLING_BOUNDARIES/GUAN.json'),
    HARV: () => import('./deferredJSON/SAMPLING_BOUNDARIES/HARV.json'),
    HEAL: () => import('./deferredJSON/SAMPLING_BOUNDARIES/HEAL.json'),
    JERC: () => import('./deferredJSON/SAMPLING_BOUNDARIES/JERC.json'),
    JORN: () => import('./deferredJSON/SAMPLING_BOUNDARIES/JORN.json'),
    KONA: () => import('./deferredJSON/SAMPLING_BOUNDARIES/KONA.json'),
    KONZ: () => import('./deferredJSON/SAMPLING_BOUNDARIES/KONZ.json'),
    LAJA: () => import('./deferredJSON/SAMPLING_BOUNDARIES/LAJA.json'),
    LENO: () => import('./deferredJSON/SAMPLING_BOUNDARIES/LENO.json'),
    MLBS: () => import('./deferredJSON/SAMPLING_BOUNDARIES/MLBS.json'),
    MOAB: () => import('./deferredJSON/SAMPLING_BOUNDARIES/MOAB.json'),
    NIWO: () => import('./deferredJSON/SAMPLING_BOUNDARIES/NIWO.json'),
    NOGP: () => import('./deferredJSON/SAMPLING_BOUNDARIES/NOGP.json'),
    OAES: () => import('./deferredJSON/SAMPLING_BOUNDARIES/OAES.json'),
    ONAQ: () => import('./deferredJSON/SAMPLING_BOUNDARIES/ONAQ.json'),
    ORNL: () => import('./deferredJSON/SAMPLING_BOUNDARIES/ORNL.json'),
    OSBS: () => import('./deferredJSON/SAMPLING_BOUNDARIES/OSBS.json'),
    PUUM: () => import('./deferredJSON/SAMPLING_BOUNDARIES/PUUM.json'),
    RMNP: () => import('./deferredJSON/SAMPLING_BOUNDARIES/RMNP.json'),
    SCBI: () => import('./deferredJSON/SAMPLING_BOUNDARIES/SCBI.json'),
    SERC: () => import('./deferredJSON/SAMPLING_BOUNDARIES/SERC.json'),
    SJER: () => import('./deferredJSON/SAMPLING_BOUNDARIES/SJER.json'),
    SOAP: () => import('./deferredJSON/SAMPLING_BOUNDARIES/SOAP.json'),
    SRER: () => import('./deferredJSON/SAMPLING_BOUNDARIES/SRER.json'),
    STEI: () => import('./deferredJSON/SAMPLING_BOUNDARIES/STEI.json'),
    STER: () => import('./deferredJSON/SAMPLING_BOUNDARIES/STER.json'),
    TALL: () => import('./deferredJSON/SAMPLING_BOUNDARIES/TALL.json'),
    TEAK: () => import('./deferredJSON/SAMPLING_BOUNDARIES/TEAK.json'),
    TOOL: () => import('./deferredJSON/SAMPLING_BOUNDARIES/TOOL.json'),
    TREE: () => import('./deferredJSON/SAMPLING_BOUNDARIES/TREE.json'),
    UKFS: () => import('./deferredJSON/SAMPLING_BOUNDARIES/UKFS.json'),
    UNDE: () => import('./deferredJSON/SAMPLING_BOUNDARIES/UNDE.json'),
    WOOD: () => import('./deferredJSON/SAMPLING_BOUNDARIES/WOOD.json'),
    WREF: () => import('./deferredJSON/SAMPLING_BOUNDARIES/WREF.json'),
    YELL: () => import('./deferredJSON/SAMPLING_BOUNDARIES/YELL.json'),
  },
  [FEATURES.WATERSHED_BOUNDARIES.KEY]: {
  },
};

/**
   importMapJSON(
     FEATURES.AQUATIC_REACHES.KEY,
     'HARV',
     (data) => { console.log('DYNAMIC JSON SUCCESS:', data); },
     (err) => { console.log('DYNAMIC JSON FAILED:', err); },
  );
*/
const SiteMapDeferredJson = (
  featureKey = '',
  siteCode = '',
  onSuccess = () => {},
  onError = () => {},
) => {
  if (!(typeof onSuccess === 'function' && typeof onError === 'function')) {
    throw new Error('SiteMapDeferredJson requires functions for success and error handlers');
  }
  if (!deferredJSON[featureKey]) {
    onError(new Error(`Feature key not supported for deferred import: ${featureKey}`));
    return;
  }
  if (typeof deferredJSON[featureKey][siteCode] !== 'function') {
    onError(new Error(`Site code: ${siteCode} is not valid for deferred feature: ${featureKey}`));
    return;
  }
  deferredJSON[featureKey][siteCode]()
    .then((module) => { onSuccess(module.default); })
    .catch(onError);
};

export default SiteMapDeferredJson;
