import { z } from 'zod';
declare const sensorPositionV1Schema: z.ZodObject<{
    'HOR.VER': z.ZodString;
    name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    start: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    end: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceDescription: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceStart: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceEnd: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    xOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    yOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    zOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    pitch: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    roll: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    azimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    referenceLatitude: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    referenceLongitude: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    referenceElevation: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    eastOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    northOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    xAzimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    yAzimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
}, "strip", z.ZodTypeAny, {
    'HOR.VER': string;
    name?: string | null | undefined;
    azimuth?: number | null | undefined;
    end?: string | null | undefined;
    start?: string | null | undefined;
    description?: string | null | undefined;
    referenceName?: string | null | undefined;
    referenceDescription?: string | null | undefined;
    referenceStart?: string | null | undefined;
    referenceEnd?: string | null | undefined;
    xOffset?: number | null | undefined;
    yOffset?: number | null | undefined;
    zOffset?: number | null | undefined;
    pitch?: number | null | undefined;
    roll?: number | null | undefined;
    referenceLatitude?: number | null | undefined;
    referenceLongitude?: number | null | undefined;
    referenceElevation?: number | null | undefined;
    eastOffset?: number | null | undefined;
    northOffset?: number | null | undefined;
    xAzimuth?: number | null | undefined;
    yAzimuth?: number | null | undefined;
}, {
    'HOR.VER': string;
    name?: string | null | undefined;
    azimuth?: string | null | undefined;
    end?: string | null | undefined;
    start?: string | null | undefined;
    description?: string | null | undefined;
    referenceName?: string | null | undefined;
    referenceDescription?: string | null | undefined;
    referenceStart?: string | null | undefined;
    referenceEnd?: string | null | undefined;
    xOffset?: string | null | undefined;
    yOffset?: string | null | undefined;
    zOffset?: string | null | undefined;
    pitch?: string | null | undefined;
    roll?: string | null | undefined;
    referenceLatitude?: string | null | undefined;
    referenceLongitude?: string | null | undefined;
    referenceElevation?: string | null | undefined;
    eastOffset?: string | null | undefined;
    northOffset?: string | null | undefined;
    xAzimuth?: string | null | undefined;
    yAzimuth?: string | null | undefined;
}>;
declare const sensorPositionV2Schema: z.ZodObject<{
    'HOR.VER': z.ZodString;
    sensorLocationID: z.ZodString;
    sensorLocationDescription: z.ZodNullable<z.ZodString>;
    positionStartDateTime: z.ZodNullable<z.ZodString>;
    positionEndDateTime: z.ZodNullable<z.ZodString>;
    referenceLocationID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDDescription: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDStartDateTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDEndDateTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    xOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    yOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    zOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    pitch: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    roll: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    azimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodString>, number | null | undefined, string | null>>;
    locationReferenceLatitude: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    locationReferenceLongitude: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    locationReferenceElevation: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    eastOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    northOffset: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    xAzimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
    yAzimuth: z.ZodNullable<z.ZodEffects<z.ZodNullable<z.ZodOptional<z.ZodString>>, number | null | undefined, string | null | undefined>>;
}, "strip", z.ZodTypeAny, {
    'HOR.VER': string;
    sensorLocationID: string;
    sensorLocationDescription: string | null;
    positionStartDateTime: string | null;
    positionEndDateTime: string | null;
    azimuth?: number | null | undefined;
    xOffset?: number | null | undefined;
    yOffset?: number | null | undefined;
    zOffset?: number | null | undefined;
    pitch?: number | null | undefined;
    roll?: number | null | undefined;
    eastOffset?: number | null | undefined;
    northOffset?: number | null | undefined;
    xAzimuth?: number | null | undefined;
    yAzimuth?: number | null | undefined;
    referenceLocationID?: string | null | undefined;
    referenceLocationIDDescription?: string | null | undefined;
    referenceLocationIDStartDateTime?: string | null | undefined;
    referenceLocationIDEndDateTime?: string | null | undefined;
    locationReferenceLatitude?: number | null | undefined;
    locationReferenceLongitude?: number | null | undefined;
    locationReferenceElevation?: number | null | undefined;
}, {
    azimuth: string | null;
    'HOR.VER': string;
    xOffset: string | null;
    yOffset: string | null;
    zOffset: string | null;
    pitch: string | null;
    roll: string | null;
    sensorLocationID: string;
    sensorLocationDescription: string | null;
    positionStartDateTime: string | null;
    positionEndDateTime: string | null;
    eastOffset?: string | null | undefined;
    northOffset?: string | null | undefined;
    xAzimuth?: string | null | undefined;
    yAzimuth?: string | null | undefined;
    referenceLocationID?: string | null | undefined;
    referenceLocationIDDescription?: string | null | undefined;
    referenceLocationIDStartDateTime?: string | null | undefined;
    referenceLocationIDEndDateTime?: string | null | undefined;
    locationReferenceLatitude?: string | null | undefined;
    locationReferenceLongitude?: string | null | undefined;
    locationReferenceElevation?: string | null | undefined;
}>;
export type SensorPositionV1Type = z.infer<typeof sensorPositionV1Schema>;
export type SensorPositionV2Type = z.infer<typeof sensorPositionV2Schema>;
export { sensorPositionV1Schema, sensorPositionV2Schema, };
