import { z } from 'zod';
declare const sensorPositionV1Schema: z.ZodObject<{
    'HOR.VER': z.ZodString;
    name: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    start: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    end: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceName: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceDescription: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceStart: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceEnd: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    xOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    yOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    zOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    pitch: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    roll: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    azimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    referenceLatitude: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    referenceLongitude: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    referenceElevation: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    eastOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    northOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    xAzimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    yAzimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
}, z.core.$strip>;
declare const sensorPositionV2Schema: z.ZodObject<{
    'HOR.VER': z.ZodString;
    sensorLocationID: z.ZodString;
    sensorLocationDescription: z.ZodNullable<z.ZodString>;
    positionStartDateTime: z.ZodNullable<z.ZodString>;
    positionEndDateTime: z.ZodNullable<z.ZodString>;
    referenceLocationID: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDDescription: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDStartDateTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    referenceLocationIDEndDateTime: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    xOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    yOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    zOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    pitch: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    roll: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    azimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodString>, z.ZodTransform<number | null | undefined, string | null>>>;
    locationReferenceLatitude: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    locationReferenceLongitude: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    locationReferenceElevation: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    eastOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    northOffset: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    xAzimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
    yAzimuth: z.ZodNullable<z.ZodPipe<z.ZodNullable<z.ZodOptional<z.ZodString>>, z.ZodTransform<number | null | undefined, string | null | undefined>>>;
}, z.core.$strip>;
export type SensorPositionV1Type = z.infer<typeof sensorPositionV1Schema>;
export type SensorPositionV2Type = z.infer<typeof sensorPositionV2Schema>;
export { sensorPositionV1Schema, sensorPositionV2Schema, };
